import 'dart:convert';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

class Dataget extends StatefulWidget {
  @override
  _DatagetState createState() => _DatagetState();
}

class _DatagetState extends State<Dataget> {
  Future<Autogenerated> futureAlbum;
  @override
  void initState() {
    futureAlbum = fetchAlbum();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: FutureBuilder<Autogenerated>(
          future: futureAlbum,
          builder: (context, snapshot) {
            if (snapshot.hasData) {
              return Text(snapshot.data.toJson().toString());
            } else if (snapshot.hasError) {
              return Text("${snapshot.error}");
            }
            return CircularProgressIndicator();
          },
        ),
      ),
    );
  }
}

// class MyStock {
//   final open;
//   final close;
//   final height;
//   final low;

//   MyStock({this.height, this.low, this.open, this.close});

//   factory MyStock.fromJson(Map<String, dynamic> json) {
//     return MyStock(
//         open: json['o'], close: json["c"], height: json['h'], low: json['l']);
//   }
// }

Future<Autogenerated> fetchAlbum() async {
  final response = await http.get(
    'https://api.polygon.io/v2/aggs/grouped/locale/us/market/stocks/2020-10-14?unadjusted=true&apiKey=EKokJZvTdmf4FFTaRXRxgo8Tli8oR0pL',
    headers: {
      HttpHeaders.authorizationHeader: "EKokJZvTdmf4FFTaRXRxgo8Tli8oR0pL"
    },
  );

  if (response.statusCode == 200) {
    // print(response.body);
    return Autogenerated.fromJson(jsonDecode(response.body));
  } else {
    throw Exception('Failed to load album');
  }
}

class Autogenerated {
  String status;
  int queryCount;
  int resultsCount;
  bool adjusted;
  List<Results> results;

  Autogenerated(
      {this.status,
      this.queryCount,
      this.resultsCount,
      this.adjusted,
      this.results});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    queryCount = json['queryCount'];
    resultsCount = json['resultsCount'];
    adjusted = json['adjusted'];
    if (json['results'] != null) {
      results = new List<Results>();
      json['results'].forEach((v) {
        results.add(new Results.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['status'] = this.status;
    data['queryCount'] = this.queryCount;
    data['resultsCount'] = this.resultsCount;
    data['adjusted'] = this.adjusted;
    if (this.results != null) {
      data['results'] = this.results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Results {
  String t;
  Results({
    this.t,
  });

  Results.fromJson(Map<String, dynamic> json) {
    t = json['T'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['T'] = this.t;
    print('_  - - -- - - - -- - - - - - -  - - - - - - - - - - - - - - ');
    print(data);
    print('_  - - -- - - - -- - - - - - -  - - - - - - - - - - - - - - ');

    return data;
  }
}

// import 'dart:convert';
// import 'package:flutter/material.dart';
// import 'package:http/http.dart' as http;

// class Dataget extends StatefulWidget {
//   @override
//   _DatagetState createState() => _DatagetState();
// }

// class _DatagetState extends State<Dataget> {
//   var info;
//   void gettt() async {
//     var url = 'https://ifsc.razorpay.com/KARB0000001';
//     var response = await http.get(url);
//     print(response.body);
//     info = response.body;
//   }

//   Future<mybank> futureAlbum;
//   @override
//   void initState() {
//     gettt();
//     futureAlbum = fetchAlbum();
//     super.initState();
//   }

//   @override
//   Widget build(BuildContext context) {
//     return Scaffold(
//       body: Center(
//         child: FutureBuilder<mybank>(
//           future: futureAlbum,
//           builder: (context, snapshot) {
//             if (snapshot.hasData) {
//               return Text(snapshot.data.bank);
//             } else if (snapshot.hasError) {
//               return Text("${snapshot.error}");
//             }
//             return CircularProgressIndicator();
//           },
//         ),
//       ),
//     );
//   }
// }

// class mybank {
//   final bank;
//   final contact;

//   mybank({this.bank, this.contact});

//   factory mybank.fromJson(Map<String, dynamic> json) {
//     return mybank(bank: json['BANK'], contact: json["CONTACT"]);
//   }
// }

// Future<mybank> fetchAlbum() async {
//   final response = await http.get('https://ifsc.razorpay.com/KARB0000001');

//   if (response.statusCode == 200) {
//     return mybank.fromJson(jsonDecode(response.body));
//   } else {
//     throw Exception('Failed to load album');
//   }
// }
